### ISSUE TITLE
could not find pytorch using python 3.7 on Raspian 10 buster

### ISSUE THREAD

**Issue by legitaxes** [pyesonekyaw/CZ3004-SC2079-MDP-Algorithm#1]
I tried to run pip install -r requirements but I keep getting the error where it tells me that it 
"could find a version that satisfy the requirement torch==1.7.0 (from versions: none)"

I believe this issue happens because pytorch for some reason could not be found in the repository in piwheels.

I also tried the command using -f on pip install to link directly to pytorch installation site, but it still didn't work.

is there any solution to this problem?

Thanks in advance!

**Comment by pyesonekyaw** [comment]
Hello, the algorithm API is not meant to be run on the Raspberry Pi. It's meant to be run on a PC and the Raspi communicates with it through GET/POST requests. Running it on the Raspi is technically possible but definitely not recommended, will take too long to get the shortest path. 

For your specific problem, you can probably follow [the guide here](https://docs.ultralytics.com/guides/raspberry-pi/) by Ultralytics.

**Comment by legitaxes** [comment]
Okay! Thanks for the prompt reply! 💯 
Will figure it from here with my team!
